version: '3.8'

services:
  # 개발 환경에서는 프론트엔드를 로컬에서 직접 실행
  # npm run dev 또는 live-server 사용
  
  # 백엔드 (개발모드)
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-backend-dev
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - JWT_SECRET=qr-entrance-secret-key-2025
      - ADMIN_PASSWORD=admin123
      - PASSWORD_SALT=qr-entrance-salt-2025
      - TOKEN_EXPIRY=24h
      - NODE_ENV=development
      - USE_DATABASE=true
      - BACKUP_ON_START=false
    volumes:
      # 개발 모드에서는 소스 코드를 마운트하여 실시간 변경 반영
      - ./backend:/app/backend
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: npm run dev
    networks:
      - qr-network-dev

networks:
  qr-network-dev:
    driver: bridge