services:
  # 프론트엔드 (Nginx)
  frontend:
    image: nginx:alpine
    container_name: qr-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - qr-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  # 백엔드 (단일 서비스)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - JWT_SECRET=qr-entrance-secret-key-2025
      - ADMIN_PASSWORD=admin123
      - PASSWORD_SALT=qr-entrance-salt-2025
      - TOKEN_EXPIRY=24h
      - USE_DATABASE=true
      - BACKUP_ON_START=false
    volumes:
      - ./backend/src/data:/app/backend/src/data
      - ./backend/src/data/backups:/app/backend/src/data/backups
    networks:
      - qr-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:5001/api/info"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

networks:
  qr-network:
    driver: bridge